### ISSUE TITLE
Unable to launch due to gl issues

### ISSUE THREAD

**Issue by brecert** [12Boti/nix-minecraft#7]
With `vanilla10` and `vanilla12` I'm unable to launch, likely due to not being able to find a gl context for some reason.

```
[04:16:25] [Client thread/INFO]: Setting user: bree
[04:16:29] [Client thread/INFO]: LWJGL Version: 2.9.4
[04:16:29] [Client thread/ERROR]: Couldn't set pixel format
org.lwjgl.LWJGLException: Could not choose GLX13 config
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.initDefaultPeerInfo(Native Method) ~[ps0r9jxxs9gpqqwz6p2pnkdvwg2zga1g-lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.LinuxDisplayPeerInfo.<init>(LinuxDisplayPeerInfo.java:61) ~[ps0r9jxxs9gpqqwz6p2pnkdvwg2zga1g-lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.LinuxDisplay.createPeerInfo(LinuxDisplay.java:828) ~[ps0r9jxxs9gpqqwz6p2pnkdvwg2zga1g-lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61) ~[ps0r9jxxs9gpqqwz6p2pnkdvwg2zga1g-lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:846) ~[ps0r9jxxs9gpqqwz6p2pnkdvwg2zga1g-lwjgl-2.9.4-nightly-20150209.jar:?]
        at org.lwjgl.opengl.Display.create(Display.java:757) ~[ps0r9jxxs9gpqqwz6p2pnkdvwg2zga1g-lwjgl-2.9.4-nightly-20150209.jar:?]
        at bcx.ap(SourceFile:585) [0qvplp7mp13mlbqi81h6213d3vn2hpr4-client.jar:?]
        at bcx.an(SourceFile:434) [0qvplp7mp13mlbqi81h6213d3vn2hpr4-client.jar:?]
        at bcx.a(SourceFile:381) [0qvplp7mp13mlbqi81h6213d3vn2hpr4-client.jar:?]
        at net.minecraft.client.main.Main.main(SourceFile:124) [0qvplp7mp13mlbqi81h6213d3vn2hpr4-client.jar:?]
...

Details:
        Minecraft Version: 1.10.2
        Operating System: Linux (amd64) version 5.10.77
        Java Version: 1.8.0_272, Oracle Corporation
        Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
        Memory: 163520360 bytes (155 MB) / 222822400 bytes (212 MB) up to 3648520192 bytes (3479 MB)
        JVM Flags: 0 total; 
        IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
        Launched Version: 1.10.2
        LWJGL: 2.9.4
        OpenGL: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
        GL Caps: 
        Using VBOs: Yes
        Is Modded: Probably not. Jar signature remains and client brand is untouched.
        Type: Client (map_client.txt)
        Resource Packs: 
        Current Language: ~~ERROR~~ NullPointerException: null
        Profiler Position: N/A (disabled)
        CPU: <unknown>
 ```

With `vanilla16` I end up with a similar problem.

```
Minecraft
GLFW error 65542: GLX: No GLXFBConfigs returned.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
press enter to continue 

Minecraft
GLFW error 65545: GLX: Failed to find a suitable GLXFBConfig.
Please make sure you have up-to-date drivers (see aka.ms/mcdriver for instructions).
press enter to continue 

[04:20:15] [Render thread/WARN]: Failed to create window: 
dgy$a: GLFW error 65545: GLX: Failed to find a suitable GLXFBConfig
        at dgy.b(SourceFile:216) ~[6yw0bp5sdz32n6vld7d0xhswb3gvmjin-client.jar:?]
        at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:36) ~[g2wjvzbmas27jf2lk94j9pk1ayxhla68-lwjgl-glfw-3.2.2.jar:build 10]
        at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[p22p0imrg6brzvz9p8l03b8ys34rwz56-lwjgl-3.2.2.jar:build 10]
        at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:1714) ~[g2wjvzbmas27jf2lk94j9pk1ayxhla68-lwjgl-glfw-3.2.2.jar:build 10]
        at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:1897) ~[g2wjvzbmas27jf2lk94j9pk1ayxhla68-lwjgl-glfw-3.2.2.jar:build 10]
        at dgy.<init>(SourceFile:90) ~[6yw0bp5sdz32n6vld7d0xhswb3gvmjin-client.jar:?]
        at ecn.a(SourceFile:21) ~[6yw0bp5sdz32n6vld7d0xhswb3gvmjin-client.jar:?]
        at dlx.<init>(SourceFile:449) ~[6yw0bp5sdz32n6vld7d0xhswb3gvmjin-client.jar:?]
        at net.minecraft.client.main.Main.main(SourceFile:177) [6yw0bp5sdz32n6vld7d0xhswb3gvmjin-client.jar:?]
```

I had some similar issues the other day with multimc, however after editing my nixconfig those issues have since disappeared.
It's likely possible this may be an issue with my hardware and installation rather than this project, but I'm really not sure.

**Comment by 12Boti** [comment]
Did you reboot since you changed your config? I think this is a driver issue. Does multimc work with the same versions?

**Comment by brecert** [comment]
> Did you reboot since you changed your config?

Yes, I've also tried a few other solutions like using nixGL


> Does multimc work with the same versions?

It does

I also tried it with the vanilla launcher and it worked there too.

> I think this is a driver issue

It think it's likely. I made a simple (naive) nix derivation for [minekiss](https://github.com/Riteo/minekiss/blob/master/minekiss) and ran into the same issue.

Another thing of note is that when I was checking `glxinfo`, I noticed `nix-shell` and `nix shell` had different behaviors.
```
$ nix-shell -p glxinfo
$ glxinfo | grep -i opengl
Error: couldn't find RGB GLX visual or fbconfig
```
```
$ nix shell nixpkgs#glxinfo
$ glxinfo | grep -i opengl
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) UHD Graphics 630 (CFL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 21.2.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.6 (Compatibility Profile) Mesa 21.2.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 21.2.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:
```

**Comment by 12Boti** [comment]
Can you try with the [no-clean-env branch](https://github.com/12Boti/nix-minecraft/tree/no-clean-env)?

**Comment by brecert** [comment]
Sadly the same error messages happens on all the vanilla ci versions.
